# =============================================================================
# Pipeline GitHub Actions — Version commentée pour apprendre
# =============================================================================
#
# Ce fichier est une copie pédagogique du pipeline réel (.github/workflows/ci.yml).
# Chaque ligne est expliquée pour que tu comprennes ce qui se passe.
#
# Ce fichier ne s'exécute PAS (il n'est pas dans .github/workflows/).
#     C'est un support d'apprentissage.
# =============================================================================

# --- NOM DU PIPELINE ---
# Le nom apparaît dans l'onglet "Actions" de GitHub.
name: CI — DevOps Rooms

# --- DÉCLENCHEUR ---
# "on" définit QUAND le pipeline se lance.
# Ici : à chaque push sur main, et à chaque pull request vers main.
on:
  push:
    branches: [main]
    # Quand quelqu'un pousse du code directement sur la branche main
  pull_request:
    branches: [main]
    # Quand quelqu'un ouvre ou met à jour une PR vers main

# --- JOBS ---
# Un job est un ensemble d'étapes qui s'exécutent sur une machine.
# Tu peux avoir plusieurs jobs, mais ici on en a un seul.
jobs:
  check-structure:
    # Nom affiché dans l'interface GitHub
    name: "Vérifier la structure du repo"

    # --- MACHINE ---
    # runs-on = sur quelle machine le job tourne
    # ubuntu-latest = une machine Linux dans le cloud de GitHub (gratuite)
    runs-on: ubuntu-latest

    # --- ÉTAPES ---
    # Les étapes s'exécutent dans l'ordre, l'une après l'autre.
    steps:

      # ÉTAPE 1 : Récupérer le code
      # "uses" = utiliser une action existante (faite par quelqu'un d'autre)
      # actions/checkout@v4 = clone le repo sur la machine
      # Sans ça, le pipeline n'a pas accès au code !
      - name: Checkout du code
        uses: actions/checkout@v4

      # ÉTAPE 2 : Vérifier que les fichiers importants existent
      # "run" = exécuter des commandes shell (bash)
      # Si une commande échoue (exit 1), le pipeline passe en ROUGE
      - name: Vérifier les fichiers obligatoires
        run: |
          echo "=== Vérification des fichiers ==="
          ERREURS=0

          # On vérifie chaque fichier un par un
          for f in README.md LICENSE PROGRESS.md docs/START-HERE.md docs/glossary.md; do
            if [ -f "$f" ]; then
              echo "$f existe"
            else
              echo "$f manquant !"
              ERREURS=$((ERREURS + 1))
            fi
          done

          # Si au moins un fichier manque, on fait échouer le pipeline
          if [ $ERREURS -gt 0 ]; then
            echo "Il manque $ERREURS fichier(s)."
            exit 1
            # exit 1 = "il y a une erreur" → le pipeline devient rouge
          fi

          echo "Tout est bon !"
          # Si on arrive ici, tout est vert

      # ÉTAPE 3 : Vérifier que les rooms ont un README
      - name: Vérifier les rooms
        run: |
          echo "=== Vérification des rooms ==="
          for i in 00 01 02 03 04 05 06 07 08 09 10 11; do
            ROOM="rooms/room-$i-*/README.md"
            if ls $ROOM 1>/dev/null 2>&1; then
              echo "Room $i OK"
            else
              echo "Room $i : pas de README"
              exit 1
            fi
          done
          echo "Toutes les rooms sont complètes."

      # ÉTAPE 4 : Vérifier que les fichiers markdown ne sont pas vides
      - name: Vérifier le contenu markdown
        run: |
          echo "=== Vérification du contenu ==="
          VIDES=0
          TOTAL=0
          for f in $(find . -name "*.md" -not -path "./.git/*"); do
            TOTAL=$((TOTAL + 1))
            if [ ! -s "$f" ]; then
              echo "Fichier vide : $f"
              VIDES=$((VIDES + 1))
            fi
          done
          echo "$TOTAL fichiers markdown vérifiés."
          if [ $VIDES -gt 0 ]; then
            echo "$VIDES fichier(s) vide(s) !"
            exit 1
          fi
          echo "Aucun fichier vide."

# =============================================================================
# RÉSUMÉ
#
# Ce pipeline fait 4 choses :
# 1. Récupère le code (checkout)
# 2. Vérifie que les fichiers obligatoires existent
# 3. Vérifie que chaque room a un README
# 4. Vérifie que les fichiers markdown ne sont pas vides
#
# Si tout est OK → vert (le code peut être mergé)
# Si quelque chose manque → rouge (il faut corriger avant de merger)
#
# Le vrai pipeline est dans : .github/workflows/ci.yml
# =============================================================================
